import vk_api
from vk_api.keyboard import VkKeyboard, VkKeyboardColor

mainmenu = VkKeyboard(one_time=False)
mainmenu.add_button(label="Профиль")
mainmenu.add_line()
mainmenu.add_button(label="Бонус", color=VkKeyboardColor.PRIMARY)
mainmenu.add_button(label="Банк")
mainmenu.add_button(label="Баланс", color=VkKeyboardColor.POSITIVE)
mainmenu.add_line()
mainmenu.add_button(label="Магазин")
mainmenu.add_button(label="Работа")
mainmenu.add_button(label="Игры")
mainmenu.add_line()
mainmenu.add_button(label="Уровни")
mainmenu.add_button(label="Ферма")
mainmenu.add_button(label="Стата")
mainmenu.add_button(label="Топ")
mainmenu.add_line()
mainmenu.add_button(label="Админпанель", color=VkKeyboardColor.NEGATIVE)
mainmenu.add_button(label="Команды", color=VkKeyboardColor.SECONDARY)

mainworkmenu = VkKeyboard(one_time=False)
mainworkmenu.add_button(label="Работать", color=VkKeyboardColor.PRIMARY)
mainworkmenu.add_line()
mainworkmenu.add_button(label="Устроиться", color=VkKeyboardColor.POSITIVE)
mainworkmenu.add_line()
mainworkmenu.add_button(label="Уволиться", color=VkKeyboardColor.NEGATIVE)
mainworkmenu.add_line()
mainworkmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.PRIMARY)

worksmenu = VkKeyboard(one_time=False)
worksmenu.add_button(label="Устроиться 1")
worksmenu.add_button(label="Устроиться 2")
worksmenu.add_line()
worksmenu.add_button(label="Устроиться 3")
worksmenu.add_button(label="Устроиться 4")
worksmenu.add_line()
worksmenu.add_button(label="Устроиться 5")
worksmenu.add_button(label="Устроиться 6")
worksmenu.add_line()
worksmenu.add_button(label="Устроиться 7")
worksmenu.add_button(label="Устроиться 8")
worksmenu.add_line()
worksmenu.add_button(label="Устроиться 9")
worksmenu.add_button(label="Устроиться 10")
worksmenu.add_line()
worksmenu.add_button(label="⬅ Работа", color=VkKeyboardColor.PRIMARY)
worksmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)

shopmenu = VkKeyboard(one_time=False)
shopmenu.add_button(label="Машины")
shopmenu.add_line()
shopmenu.add_button(label="Телефоны")
shopmenu.add_line()
shopmenu.add_button(label="Дома")
shopmenu.add_line()
shopmenu.add_button(label="Видеокарты")
shopmenu.add_line()
shopmenu.add_button(label="Биткоины")
shopmenu.add_line()
shopmenu.add_button(label="Продать", color=VkKeyboardColor.NEGATIVE)
shopmenu.add_line()
shopmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)

carsmenu = VkKeyboard(one_time=False)
carsmenu.add_button(label="Кмашину 1")
carsmenu.add_button(label="Кмашину 2")
carsmenu.add_button(label="Кмашину 3")
carsmenu.add_line()
carsmenu.add_button(label="Кмашину 4")
carsmenu.add_button(label="Кмашину 5")
carsmenu.add_button(label="Кмашину 6")
carsmenu.add_line()
carsmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)
carsmenu.add_button(label="⬅ Магазин", color=VkKeyboardColor.PRIMARY)

phonemenu = VkKeyboard(one_time=False)
phonemenu.add_button(label="Ктел 1")
phonemenu.add_button(label="Ктел 2")
phonemenu.add_button(label="Ктел 3")
phonemenu.add_line()
phonemenu.add_button(label="Ктел 4")
phonemenu.add_button(label="Ктел 5")
phonemenu.add_line()
phonemenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)
phonemenu.add_button(label="⬅ Магазин", color=VkKeyboardColor.PRIMARY)

homemenu = VkKeyboard(one_time=False)
homemenu.add_button(label="Кдом 1")
homemenu.add_button(label="Кдом 2")
homemenu.add_button(label="Кдом 3")
homemenu.add_line()
homemenu.add_button(label="Кдом 4")
homemenu.add_button(label="Кдом 5")
homemenu.add_button(label="Кдом 6")
homemenu.add_line()
homemenu.add_button(label="Кдом 7")
homemenu.add_button(label="Кдом 8")
homemenu.add_line()
homemenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)
homemenu.add_button(label="⬅ Магазин", color=VkKeyboardColor.PRIMARY)

gpumenu = VkKeyboard(one_time=False)
gpumenu.add_button(label="Ккарту 1")
gpumenu.add_button(label="Ккарту 2")
gpumenu.add_button(label="Ккарту 3")
gpumenu.add_line()
gpumenu.add_button(label="Ккарту 4")
gpumenu.add_button(label="Ккарту 5")
gpumenu.add_button(label="Ккарту 6")
gpumenu.add_line()
gpumenu.add_button(label="&#12288;")
gpumenu.add_line()
gpumenu.add_button(label="Ккарту 7")
gpumenu.add_button(label="Ккарту 8")
gpumenu.add_button(label="Ккарту 9")
gpumenu.add_line()
gpumenu.add_button(label="Ккарту 10")
gpumenu.add_button(label="Ккарту 11")
gpumenu.add_button(label="Ккарту 12")
gpumenu.add_line()
gpumenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)
gpumenu.add_button(label="⬅ Магазин", color=VkKeyboardColor.PRIMARY)

sellmenu = VkKeyboard(one_time=False)
sellmenu.add_button(label="Пмашину", color=VkKeyboardColor.NEGATIVE)
sellmenu.add_line()
sellmenu.add_button(label="Птел", color=VkKeyboardColor.NEGATIVE)
sellmenu.add_line()
sellmenu.add_button(label="Пдом", color=VkKeyboardColor.NEGATIVE)
sellmenu.add_line()
sellmenu.add_button(label="Пкарту", color=VkKeyboardColor.NEGATIVE)
sellmenu.add_line()
sellmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)
sellmenu.add_button(label="⬅ Магазин", color=VkKeyboardColor.PRIMARY)

farmmenu = VkKeyboard(one_time=False)
farmmenu.add_button(label="Сбитки")
farmmenu.add_line()
farmmenu.add_button(label="♻ Обновить")
farmmenu.add_line()
farmmenu.add_button(label="Биткоины")
farmmenu.add_line()
farmmenu.add_button(label="Видеокарты", color=VkKeyboardColor.PRIMARY)
farmmenu.add_line()
farmmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)

adminmenu = VkKeyboard(one_time=False)
adminmenu.add_button(label="Пoлная накрутка", color=VkKeyboardColor.POSITIVE)
adminmenu.add_button(label="Oбнуление", color=VkKeyboardColor.NEGATIVE)
adminmenu.add_line()
adminmenu.add_button(label="Сбал 1000000")
adminmenu.add_line()
adminmenu.add_button(label="Сбитк 5000")
adminmenu.add_line()
adminmenu.add_button(label="Слвл 5")
adminmenu.add_line()
adminmenu.add_button(label="Сопыт 500")
adminmenu.add_line()
adminmenu.add_button(label="Users")
adminmenu.add_line()
adminmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)

monetkasidemenu = VkKeyboard(one_time=False)
monetkasidemenu.add_button(label="Орел")
monetkasidemenu.add_button(label="Решка")
monetkasidemenu.add_line()
monetkasidemenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)
monetkasidemenu.add_button(label="⬅ Игры", color=VkKeyboardColor.PRIMARY)

monetkaorelmenu = VkKeyboard(one_time=False)
monetkaorelmenu.add_button(label="Монетка орел 1000")
monetkaorelmenu.add_button(label="Монетка орел 10000")
monetkaorelmenu.add_line()
monetkaorelmenu.add_button(label="Монетка орел 100000")
monetkaorelmenu.add_button(label="Монетка орел 500000")
monetkaorelmenu.add_line()
monetkaorelmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)
monetkaorelmenu.add_button(label="⬅ Игры", color=VkKeyboardColor.PRIMARY)

monetkareshkamenu = VkKeyboard(one_time=False)
monetkareshkamenu.add_button(label="Монетка решка 1000")
monetkareshkamenu.add_button(label="Монетка решка 10000")
monetkareshkamenu.add_line()
monetkareshkamenu.add_button(label="Монетка решка 100000")
monetkareshkamenu.add_button(label="Монетка решка 500000")
monetkareshkamenu.add_line()
monetkareshkamenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)
monetkareshkamenu.add_button(label="⬅ Игры", color=VkKeyboardColor.PRIMARY)

kazmenu = VkKeyboard(one_time=False)
kazmenu.add_button(label="Казино всё")
kazmenu.add_button(label="Казино половина")
kazmenu.add_line()
kazmenu.add_button(label="Казино 1000")
kazmenu.add_button(label="Казино 50000")
kazmenu.add_line()
kazmenu.add_button(label="Казино 100000")
kazmenu.add_button(label="Казино 500000")
kazmenu.add_line()
kazmenu.add_button(label="Казино 1000000")
kazmenu.add_button(label="Казино 5000000")
kazmenu.add_line()
kazmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)
kazmenu.add_button(label="⬅ Игры", color=VkKeyboardColor.PRIMARY)

gamesmenu = VkKeyboard(one_time=False)
gamesmenu.add_button(label="Монетка")
gamesmenu.add_button(label="Казино")
gamesmenu.add_line()
gamesmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)

btcmenu = VkKeyboard(one_time=False)
btcmenu.add_button(label="Кбитк все", color=VkKeyboardColor.POSITIVE)
btcmenu.add_line()
btcmenu.add_button(label="Кбитк 1")
btcmenu.add_button(label="Кбитк 10")
btcmenu.add_button(label="Кбитк 100")
btcmenu.add_line()
btcmenu.add_button(label="Пбитк все", color=VkKeyboardColor.NEGATIVE)
btcmenu.add_line()
btcmenu.add_button(label="Пбитк 1")
btcmenu.add_button(label="Пбитк 10")
btcmenu.add_button(label="Пбитк 100")
btcmenu.add_line()
btcmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)

bankmenu = VkKeyboard(one_time=False)
bankmenu.add_button(label="Банк положить всё", color=VkKeyboardColor.PRIMARY)
bankmenu.add_button(label="Банк положить половину", color=VkKeyboardColor.PRIMARY)
bankmenu.add_line()
bankmenu.add_button(label="Банк снять всё", color=VkKeyboardColor.POSITIVE)
bankmenu.add_button(label="Банк снять половину", color=VkKeyboardColor.POSITIVE)
bankmenu.add_line()
bankmenu.add_button(label="Банк баланс")
bankmenu.add_line()
bankmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)

topmenu = VkKeyboard(one_time=False)
topmenu.add_button(label="Балтоп")
topmenu.add_button(label="Битктоп")
topmenu.add_line()
topmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)

# Хакерство

mainhackmenu = VkKeyboard(one_time=False)
mainhackmenu.add_button(label="Что-то будет")
mainhackmenu.add_line()
mainhackmenu.add_button(label="Улучшение")
mainhackmenu.add_line()
mainhackmenu.add_button(label="DarkShop", color=VkKeyboardColor.PRIMARY)
mainhackmenu.add_line()
mainhackmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)

dsmenu = VkKeyboard(one_time=False)
dsmenu.add_button(label="Компы")
dsmenu.add_line()
dsmenu.add_button(label="VPN")
dsmenu.add_line()
dsmenu.add_button(label="Убежища")
dsmenu.add_line()
dsmenu.add_button(label="Прoдать", color=VkKeyboardColor.NEGATIVE)
dsmenu.add_line()
dsmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)
dsmenu.add_button(label="⬅ Хакерство", color=VkKeyboardColor.PRIMARY)

compmenu = VkKeyboard(one_time=False)
compmenu.add_button(label="Ккомп 1")
compmenu.add_button(label="Ккомп 2")
compmenu.add_button(label="Ккомп 3")
compmenu.add_line()
compmenu.add_button(label="Ккомп 4")
compmenu.add_button(label="Ккомп 5")
compmenu.add_line()
compmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)
compmenu.add_button(label="⬅ DarkShop", color=VkKeyboardColor.PRIMARY)

vpnmenu = VkKeyboard(one_time=False)
vpnmenu.add_button(label="Квпн 1")
vpnmenu.add_button(label="Квпн 2")
vpnmenu.add_button(label="Квпн 3")
vpnmenu.add_line()
vpnmenu.add_button(label="Квпн 4")
vpnmenu.add_button(label="Квпн 5")
vpnmenu.add_line()
vpnmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)
vpnmenu.add_button(label="⬅ DarkShop", color=VkKeyboardColor.PRIMARY)

shltrmenu = VkKeyboard(one_time=False)
shltrmenu.add_button(label="Кубежище 1")
shltrmenu.add_button(label="Кубежище 2")
shltrmenu.add_button(label="Кубежище 3")
shltrmenu.add_line()
shltrmenu.add_button(label="Кубежище 4")
shltrmenu.add_button(label="Кубежище 5")
shltrmenu.add_line()
shltrmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)
shltrmenu.add_button(label="⬅ DarkShop", color=VkKeyboardColor.PRIMARY)

selldarkmenu = VkKeyboard(one_time=False)
selldarkmenu.add_button(label="Пкомп")
selldarkmenu.add_line()
selldarkmenu.add_button(label="Пвпн")
selldarkmenu.add_line()
selldarkmenu.add_button(label="Пубежище")
selldarkmenu.add_line()
selldarkmenu.add_button(label="🏠 Главное меню", color=VkKeyboardColor.POSITIVE)
selldarkmenu.add_button(label="⬅ DarkShop", color=VkKeyboardColor.PRIMARY)

uplmenu = VkKeyboard(one_time=False)
uplmenu.add_button(label="💊 ХП")
uplmenu.add_button(label="🔫 Урон")
uplmenu.add_button(label="🕶 Защита")
uplmenu.add_line()
uplmenu.add_button(label="⬅ Хакерство", color=VkKeyboardColor.PRIMARY)

phpmenu = VkKeyboard(one_time=False)
phpmenu.add_button(label="Прокачать ХП")
phpmenu.add_line()
phpmenu.add_button(label="⬅ Улучшения", color=VkKeyboardColor.PRIMARY)
phpmenu.add_button(label="🏠 Хакерство", color=VkKeyboardColor.POSITIVE)

pdefmenu = VkKeyboard(one_time=False)
pdefmenu.add_button(label="Прокачать Защиту")
pdefmenu.add_line()
pdefmenu.add_button(label="⬅ Улучшения", color=VkKeyboardColor.PRIMARY)
pdefmenu.add_button(label="🏠 Хакерство", color=VkKeyboardColor.POSITIVE)

pdamagemenu = VkKeyboard(one_time=False)
pdamagemenu.add_button(label="Прокачать Урон")
pdamagemenu.add_line()
pdamagemenu.add_button(label="⬅ Улучшения", color=VkKeyboardColor.PRIMARY)
pdamagemenu.add_button(label="🏠 Хакерство", color=VkKeyboardColor.POSITIVE)
# Хакерство

errormenu = VkKeyboard(one_time=False, inline=True)
errormenu.add_button(label="Команды", color=VkKeyboardColor.POSITIVE)

bonusmenu = VkKeyboard(one_time=False, inline=True)
bonusmenu.add_button(label="Бонус", color=VkKeyboardColor.POSITIVE)